version: "3.9"

services:
  node_app:
    container_name: node_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "4800:4800"
    environment:
      - PG_DB=ai
      - PG_USER=postgres
      - PG_PASSWORD=020300
      - PG_HOST=node_db
    restart: always
    depends_on:
      - node_db

  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=020300

volumes:
  node_db_data: {}
